version: '3'

services:
 app:
   build:
     context: .
   ports:
     - "8000:8000"
   volumes:
     - ./app:/app
   command: >
       sh -c "python manage.py wait_for_db &&
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000"
   network_mode: host
   depends_on:
      - database
 database:
    container_name: database
    build:
       context: ./database
    ports:
      - "5432:5432"
    network_mode: host


